// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "2543a532-9218-42bf-a20d-40f7eec7f501");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1592053764);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1591839665);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1592053284);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1592053524);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1592053404);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1592053644);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1591545895);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1591841673);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 2);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 86820);
user_pref("browser.cache.disk.capacity", 1044480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1591454567);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4c973f3b-7e02-4fe3-ac97-5901e14d7585}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1592053259775");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1592055087775");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1592053259811");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1592056859811");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191202093317");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20191202093317");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1592053257);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1591454572208");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "6764f551d5054a1cb77d3207fc5a14c9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 09 Jun 2020 17:08:02 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1592053765);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191202093317");
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"df5f213c-7e1b-4e03-9052-97a696134305\",\"screenshots@mozilla.org\":\"07fef866-f2a0-4747-a909-682ac3d13ffe\",\"webcompat-reporter@mozilla.org\":\"998f2388-8231-4c64-903d-970f0fed2320\",\"webcompat@mozilla.org\":\"9c0363f5-f055-42ce-b559-90d3daecffdd\",\"default-theme@mozilla.org\":\"694b7a7b-6e7b-4bca-bd65-e7d6d6997bae\",\"google@search.mozilla.org\":\"972116f5-5d97-44b2-a4fa-68d8544d6359\",\"amazondotcom@search.mozilla.org\":\"cdabcb82-f2c3-4f9c-9327-c52f0b841fc4\",\"bing@search.mozilla.org\":\"ad92c5d6-18cc-44db-b18f-db7fd918dd89\",\"ddg@search.mozilla.org\":\"5fd6600d-e744-4d99-8aaa-1f6a870917a4\",\"ebay@search.mozilla.org\":\"9e8e3910-5286-48c5-8beb-4dff2d62d29e\",\"twitter@search.mozilla.org\":\"493c2fb2-8eb7-40a3-ab0a-36a14ae4cb80\",\"wikipedia@search.mozilla.org\":\"6f2caf13-0629-4d9b-a587-7d968b8a2b63\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1591842125);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1591546348);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191202093317");
user_pref("media.gmp-manager.lastCheck", 1592053737);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1591547098);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "0731e708-377c-4aa7-807a-e664fe924abb");
user_pref("security.sandbox.plugin.tempDirSuffix", "f3d7b7af-4df6-4258-917d-bacc4c872132");
user_pref("services.blocklist.pinning.checked", 1591546535);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1592006479723\"");
user_pref("services.settings.last_update_seconds", 1592053645);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1592053645);
user_pref("services.settings.main.cfr-fxa.last_check", 1592053645);
user_pref("services.settings.main.cfr.last_check", 1592053645);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1592053645);
user_pref("services.settings.main.hijack-blocklists.last_check", 1592053645);
user_pref("services.settings.main.language-dictionaries.last_check", 1592053645);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1592053645);
user_pref("services.settings.main.public-suffix-list.last_check", 1592053645);
user_pref("services.settings.main.sites-classification.last_check", 1592053645);
user_pref("services.settings.main.tippytop.last_check", 1592053645);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1592053645);
user_pref("services.settings.main.whats-new-panel.last_check", 1592053645);
user_pref("services.settings.security.onecrl.checked", 1591546535);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1591547098);
user_pref("toolkit.startup.last_success", 1592053251);
user_pref("toolkit.telemetry.cachedClientID", "988da1fa-c3d8-4be4-b5b6-714f45d5fecb");
user_pref("toolkit.telemetry.previousBuildID", "20191202093317");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "modal_variant_f");
